services: 
  db:
    image: postgres:17.4-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: team_demo
      volumes: ./backend/db/sql:/docker-entrypoint-initdb.d
      ports: 5433:5432
    
  server:
    build: ./backend
    ports:
      - 3333:3333
    volumes:
      - ./backend:/backend
    tty: true